// Official-source snapshots researched 5 October 2026. Not a live API.
const surveillance={
 checkedOn:'2026-10-05',
 countries:['Brunei Darussalam','Cambodia','Indonesia','Lao PDR','Malaysia','Myanmar','Philippines','Singapore','Thailand','Timor-Leste','Vietnam'],
 national:{name:'Indonesia',value:319009,definition:'Suspected dengue reports',period:'2026 through epidemiological week 37',cutoff:'26 September 2026, 10:00 WIB',published:'28 September 2026',source:'Ministry of Health / SKDR, week 38 situation report',page:35,url:'https://surveilans.kemkes.go.id/assets/publikasi/laporan-mingguan-situasi-terkini-penyakit-infem-dan-potensial-klb-wabah-m38-2026.pdf',note:'National total transcribed from the report summary. The province chart sums to 319,266, a difference of 257; do not recompute the national total from that chart or treat the snapshot as harmonised.'},
 jakarta:{name:'Jakarta',value:28910,definition:'Suspected dengue reports',period:'2026 through epidemiological week 37',cutoff:'26 September 2026, 10:00 WIB',published:'28 September 2026',source:'Ministry of Health / SKDR, week 38 situation report',page:42,url:'https://surveilans.kemkes.go.id/assets/publikasi/laporan-mingguan-situasi-terkini-penyakit-infem-dan-potensial-klb-wabah-m38-2026.pdf'},
 provinces:[{name:'West Java',value:65869},{name:'East Java',value:42605},{name:'Central Java',value:38554},{name:'Banten',value:31595},{name:'Jakarta',value:28910}],
 eastJakarta:{definition:'Reported DBD cases',period:'January–11 June 2026',cutoff:'11 June 2026',published:'24 July 2026',source:'Jakarta government / East Jakarta Health Subdepartment',url:'https://www.jakarta.go.id/siaran-pers-wilayah/1/4453-SP-JAKTIM-07-2026',districts:[{name:'Cakung',value:360},{name:'Matraman',value:259},{name:'Ciracas',value:217},{name:'Kramat Jati',value:198},{name:'Duren Sawit',value:195},{name:'Pulogadung',value:194},{name:'Cipayung',value:147},{name:'Pasar Rebo',value:138},{name:'Jatinegara',value:130},{name:'Makasar',value:113}],incidence:{name:'Matraman',value:141.68,unit:'cases per 100,000 residents'}},
 guidance:{title:'PSN 3M Plus',text:'Drain and clean water containers, cover water storage, and recycle or reuse items that could collect water. Follow additional prevention measures recommended by your local health authority.',url:'https://www.jakarta.go.id/siaran-pers-wilayah/1/4453-SP-JAKTIM-07-2026'},
 resources:[{title:'Indonesia dengue action plan, 2026–2029',url:'https://www.who.int/indonesia/news-room/item/30-03-2026-shaping-indonesia-s-path-towards-zero-dengue-deaths-by-2030',source:'WHO Indonesia',published:'30 March 2026'},{title:'Jakarta dengue incidence-rate dataset',url:'https://satudata.jakarta.go.id/open-data/detail?kategori=dataset&page_url=incidence-rate-ir-demam-berdarah-dengue-dbd-berdasarkan-wilayah',source:'Satu Data Jakarta',note:'Dataset directory verified; values not imported.'}]
};
