/* Login and community interactions are browser-local demonstrations. */
const experienceRender=render,experienceConnect=connect,experienceGuide=guide;
const groupSeed=[{name:'Sari',time:'09:12',text:'Welcome to the Tebet prevention group. Please keep reports focused on the site, without personal health details.'},{name:'Sari',time:'09:12',text:'This week, we are checking containers that collect water after rain.'},{name:'Bima',time:'09:16',text:'I spotted an uncovered container near the shared courtyard. I have added a sample observation for review.'},{name:'Nadya',time:'09:20',text:'I can help follow up after the local coordinator reviews it.'}];
let groupMessages=read('ds-group-messages',groupSeed);
const readingLinks=[{title:'Indonesia and WHO ramp up dengue fight with smarter surveillance',publisher:'WHO Indonesia',date:'16 May 2025',url:'https://www.who.int/indonesia/news/detail/16-05-2025-indonesia-and-who-ramp-up-dengue-fight-with-smarter-surveillance',topic:'Surveillance',description:'How health, climate and vector data can support risk mapping and local preparedness.'},{title:'Annual global dengue dynamics are related to multi-source factors revealed by a machine learning prediction analysis',publisher:'PLOS Neglected Tropical Diseases',date:'2025',url:'https://journals.plos.org/plosntds/article?id=10.1371/journal.pntd.0013232',topic:'Research',description:'A research example combining climate, population and other inputs in dengue prediction.'},{title:'Climate variation and serotype competition drive dengue outbreak dynamics in Singapore',publisher:'Nature Communications',date:'22 November 2025',url:'https://www.nature.com/articles/s41467-025-66411-6',topic:'Research',description:'Research on climate-informed dengue forecasting and long-term virus surveillance.'},{title:'Shaping Indonesia’s path towards zero dengue deaths by 2030',publisher:'WHO Indonesia',date:'30 March 2026',url:'https://www.who.int/indonesia/news-room/item/30-03-2026-shaping-indonesia-s-path-towards-zero-dengue-deaths-by-2030',topic:'Preparedness',description:'Indonesia’s dengue action planning and coordinated prevention efforts.'}];
function face(name){const colors={Nadya:'#f3bcc1',Sari:'#bfd5ef',Bima:'#bddacb'};return `<span class="group-face" style="--face:${colors[name]||'#e8d1a8'}" aria-hidden="true"><svg viewBox="0 0 48 48"><path d="M8 26C3 13 14 5 26 7s20 12 16 25S12 46 8 26" fill="var(--face)"/><circle cx="18" cy="23" r="2" fill="#192d4a"/><circle cx="30" cy="23" r="2" fill="#192d4a"/><path d="M19 31q5 4 10 0" stroke="#192d4a" fill="none" stroke-width="2" stroke-linecap="round"/></svg></span>`}
function groupChat(){const runs=groupMessages.reduce((out,m)=>{const last=out[out.length-1];if(last&&last[0].name===m.name)last.push(m);else out.push([m]);return out},[]);return `<section class="panel neighbourhood-group"><div class="group-top"><div><h2>Tebet neighbours</h2><p class="muted">Community prevention group · Demo conversation</p></div><div class="face-pile">${['Nadya','Sari','Bima'].map(face).join('')}</div></div><div class="group-messages" aria-label="Demo group messages">${runs.map(run=>`<article class="chat-run">${face(run[0].name)}<div><div class="chat-author"><strong>${escape(run[0].name)}</strong><time>${escape(run[0].time)}</time></div>${run.map(m=>`<p>${escape(m.text)}</p>`).join('')}</div></article>`).join('')}</div><form id="group-form"><label for="group-message">Message your demo group</label><div class="group-compose"><input id="group-message" required maxlength="400" placeholder="Share a prevention question or update…"><button class="primary" type="submit">Send</button></div><small>Messages stay in this browser. No one else receives them.</small></form></section>`}
connect=function(){return experienceConnect()+groupChat()};
guide=function(){return experienceGuide()+`<section class="reading-section"><div class="panel-head"><div><h2>Dengue reading room</h2><p class="muted">Published in 2025 and 2026 · External sources</p></div></div><div class="reading-grid">${readingLinks.map(a=>`<a class="reading-card" href="${a.url}" target="_blank" rel="noopener noreferrer"><span>${a.topic}</span><h3>${a.title}</h3><p>${a.description}</p><small>${a.publisher} · ${a.date}</small><strong>Read article ↗</strong></a>`).join('')}</div></section>`};
function loginView(){return `<div class="login-screen"><div class="login-brand"><img class="product-logo" src="assets/denguesense-logo.png" alt="DengueSense"> <span>Team Nyamuk Hunter</span></div><div class="login-layout"><section class="login-story"><h1>Know the risk.<br>Prepare together.</h1><p>A local outlook, a clearer next step, and a community ready to act.</p><div class="spread-stage" aria-label="DengueSense capabilities"><div class="spread-card card-predict"><small>Predict</small><strong>Look ahead</strong><svg viewBox="0 0 220 85" aria-hidden="true"><path d="M0 70L35 62L70 66L110 40L150 48L185 22L220 10" fill="none" stroke="#b73540" stroke-width="4"/><path d="M110 40L150 48L185 22L220 10V70H110Z" fill="#b7354018"/></svg><p>Explore the coming weeks</p></div><div class="spread-card card-map"><small>Visualize</small><strong>Find your focus</strong><div class="login-mini-map"><i></i><i></i><i></i></div><p>Compare neighbourhoods</p></div><div class="spread-card card-connect"><small>Connect</small><div class="face-pile">${['Nadya','Sari','Bima'].map(face).join('')}</div><strong>Act together</strong><p>Share observations and follow up</p></div></div><button class="spread-toggle secondary" id="spread-toggle" aria-expanded="false">Explore the capabilities</button></section><section class="login-form-card"><div class="login-profile">${face('Nadya')}<span>Demo profile</span></div><h2>Welcome, Nadya.</h2><p>Choose how you’d like to explore DengueSense.</p><form id="demo-login"><label for="demo-name">Display name</label><input id="demo-name" value="Nadya" readonly><label for="demo-role">Your workspace</label><select id="demo-role"><option>Community member</option><option>Health officer</option></select><div class="login-location"><span>⌖</span><div><strong>Tebet, South Jakarta</strong><small>Indonesia demo workspace</small></div></div><button class="primary red full" type="submit">Log In</button></form><p class="login-disclosure">No password needed. This is a demo profile, not a real account.</p><a href="https://github.com/bellamarbellaa/dengue-sense" target="_blank" rel="noopener">About the project ↗</a></section></div></div>`}
function bindExperience(){const avatar=$('.avatar');if(avatar){avatar.innerHTML=face('Nadya');avatar.setAttribute('role','button');avatar.setAttribute('tabindex','0');avatar.setAttribute('aria-label','Nadya demo profile');avatar.onclick=()=>modal('Nadya’s demo profile','<p>Tebet, South Jakarta. Your activity stays in this browser.</p><button class="secondary" id="demo-signout">Return to login</button>');avatar.addEventListener('click',()=>{$('#demo-signout').onclick=()=>{$('#modal').close();sessionStorage.removeItem('ds-demo-login');showLogin()}});avatar.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();avatar.click()}}}
 $('#group-form')?.addEventListener('submit',e=>{e.preventDefault();const text=$('#group-message').value.trim();if(!text)return;groupMessages.push({name:'Nadya',time:new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit'}),text});try{localStorage.setItem('ds-group-messages',JSON.stringify(groupMessages))}catch{}render();toast('Message added to your demo group')});
}
function showLogin(){document.body.classList.add('login-mode');let screen=$('#login-root');if(!screen){screen=document.createElement('div');screen.id='login-root';document.body.appendChild(screen)}screen.innerHTML=loginView();$('#spread-toggle').onclick=()=>{const expanded=$('.spread-stage').classList.toggle('spread');$('#spread-toggle').setAttribute('aria-expanded',expanded);$('#spread-toggle').textContent=expanded?'Bring cards together':'Explore the capabilities'};$('#demo-login').onsubmit=e=>{e.preventDefault();state.role=$('#demo-role').value;$('#role').value=state.role;state.area=2;sessionStorage.setItem('ds-demo-login','Nadya');document.body.classList.remove('login-mode');screen.remove();navigate(state.role==='Community member'?'connect':'dashboard')};}
render=function(){experienceRender();bindExperience()};
render();if(!sessionStorage.getItem('ds-demo-login'))showLogin();
