// Country registry and sourced surveillance are independent of demo analytics.
state.country='Indonesia';
const regionalBaseRender=render,regionalBaseBind=bind;
const fmt=v=>Number(v).toLocaleString('en-US');
function countryControls(){const container=document.querySelector('.header-right');if(!$('#country')){container.insertAdjacentHTML('afterbegin',`<label class="country-select">Country<select id="country" aria-label="Country">${surveillance.countries.map(c=>`<option ${c===state.country?'selected':''}>${c}</option>`).join('')}</select></label>`);$('#country').onchange=e=>{state.country=e.target.value;render()}}document.querySelector('.region-label').textContent=state.country==='Indonesia'?'Jakarta prototype':'ASEAN workspace';document.querySelector('.aside-intro').textContent=state.country==='Indonesia'?'Indonesia · Jakarta prototype':state.country+' · Data connection pending'}
function sourceMeta(r){return `<div class="source-meta"><span>${escape(r.definition)}</span><span>${escape(r.period)}</span><a href="${r.url}" target="_blank" rel="noopener">${escape(r.source)} · p. ${r.page}</a><span>Data cutoff: ${escape(r.cutoff)} · Published ${r.published}</span></div>`}
function surveillanceCards(){return `<section class="official-section"><div class="panel-head"><h2>Latest sourced surveillance snapshot</h2><span class="official-tag">Official reports</span></div><p class="muted">Checked 5 October 2026. Published snapshots, not a live feed. Suspected reports are not confirmed dengue cases.</p><div class="official-grid"><article class="official-card"><span>Indonesia</span><strong>${fmt(surveillance.national.value)}</strong>${sourceMeta(surveillance.national)}</article><article class="official-card"><span>Jakarta</span><strong>${fmt(surveillance.jakarta.value)}</strong>${sourceMeta(surveillance.jakarta)}</article></div><details class="data-details"><summary>Definitions and source limitations</summary><p>The Ministry report is titled week 38, but its dengue data extend through week 37. Case counts are cumulative suspected reports. They do not establish active outbreaks, confirmed infections, forecast accuracy, or a risk score.</p><p>${escape(surveillance.national.note)}</p><p>East Jakarta's separate DBD figures use an earlier cutoff and a different case definition. They must not be added to the SKDR totals.</p></details></section>`}
function localEvidence(){const r=surveillance.eastJakarta;return `<section class="panel sourced-local"><div class="panel-head"><h2>East Jakarta reported DBD cases</h2><span class="official-tag">Local government report</span></div><p class="muted">${r.period} · Published ${r.published}. Historical snapshot, not today's active cases.</p><div class="district-bars">${r.districts.map(d=>`<div class="district-bar"><span>${d.name}</span><div><i style="width:${d.value/360*100}%"></i></div><strong>${d.value}</strong></div>`).join('')}</div><p class="note">Cakung has the highest count in this snapshot. The release identifies Matraman as having the highest incidence rate: <strong>141.68 per 100,000 residents</strong>. Counts and population-adjusted rates answer different questions. <a href="${r.url}" target="_blank" rel="noopener">Read the official release</a>.</p></section>`}
function provincialEvidence(){return `<section class="panel"><h2>Five highest province counts in the source chart</h2><p class="muted">Suspected dengue reports, 2026 through week 37.</p><div class="district-bars">${surveillance.provinces.map(d=>`<div class="district-bar"><span>${d.name}</span><div><i style="width:${d.value/65869*100}%"></i></div><strong>${fmt(d.value)}</strong></div>`).join('')}</div><p class="note">Source: Ministry of Health week 38 report, p. 42. These are cumulative counts, not incidence rates or forecast priorities.</p></section>`}
function regionalEmpty(){const sourceLink='https://www.who.int/westernpacific/wpro-emergencies/surveillance/dengue';return heading('ASEAN workspace',state.country,'The interface supports a country-specific workspace. This country has no connected surveillance or forecasting data in the current prototype.')+`<section class="panel regional-empty"><div class="regional-emblem">${escape(state.country)}</div><h2>Country data connection pending</h2><p>No case totals, risk scores, or forecasts are generated for this country. Indonesia, with a Jakarta focus, is the implemented demonstration.</p><div class="country-capabilities"><div><strong>PREDICT</strong><span>Requires local case history and forecast validation</span></div><div><strong>VISUALIZE</strong><span>Requires geographic data and compatible case definitions</span></div><div><strong>GUIDE</strong><span>Requires country-approved guidance</span></div><div><strong>CONNECT</strong><span>Requires local reporting and verification arrangements</span></div></div><button class="primary" id="return-indonesia">Explore Indonesia prototype</button><p class="note"><a href="${sourceLink}" target="_blank" rel="noopener">WHO regional dengue surveillance directory</a>. Country-specific sources and case definitions must be reviewed before connecting data.</p></section>`}
render=function(){countryControls();if(state.country!=='Indonesia'){document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.tab===state.tab));$('#content').innerHTML=regionalEmpty();$('#return-indonesia').onclick=()=>{state.country='Indonesia';$('#country').value='Indonesia';state.tab='dashboard';render()};return}regionalBaseRender();if(state.tab==='dashboard')$('#content').insertAdjacentHTML('afterbegin',surveillanceCards());if(state.tab==='dashboard')$('#content').insertAdjacentHTML('beforeend',`<div class="grid real-data-grid">${provincialEvidence()}${localEvidence()}</div>`);if(state.tab==='visualize')$('#content').insertAdjacentHTML('beforeend',localEvidence());if(state.tab==='guide')$('#content').insertAdjacentHTML('afterbegin',`<section class="panel approved-guidance"><span class="official-tag">Jakarta government guidance</span><h2>${surveillance.guidance.title}</h2><p>${surveillance.guidance.text}</p><a href="${surveillance.guidance.url}" target="_blank" rel="noopener">Read source guidance</a><div class="source-links">${surveillance.resources.map(r=>`<a href="${r.url}" target="_blank" rel="noopener">${r.title} · ${r.source}</a>`).join('')}</div></section>`)};
exportReport=function(){const content={product:'DengueSense prototype',country:state.country,checkedOn:surveillance.checkedOn,scope:state.country==='Indonesia'?'Jakarta demonstration':'Data connection pending',officialSnapshots:state.country==='Indonesia'?{national:surveillance.national,jakarta:surveillance.jakarta,eastJakarta:surveillance.eastJakarta}:null,simulationNotice:'Forecasts, risk scores, alerts, tasks and community reports are simulated. No live feed or trained model.',demoArea:state.country==='Indonesia'?areas[state.area].name:null};const blob=new Blob([JSON.stringify(content,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='DengueSense-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Sourced prototype report downloaded')};$('#export-global').onclick=exportReport;
document.querySelector('.demo-note').innerHTML='<a class="prototype-link" href="https://github.com/bellamarbellaa/dengue-sense#readme" target="_blank" rel="noopener noreferrer">Prototype ↗</a>'; 
const prototypeInfo=()=>modal('About this prototype','<p>Official surveillance figures on the Dashboard are published snapshots, with reporting periods and sources. Forecast curves, environmental readings, risk scores and rewards are sample data for demonstrating the product; a trained forecasting model is not connected.</p><p>Reports, alerts, discussions and checklists are saved in this browser. They are not sent to health authorities. The map is schematic, and other ASEAN country workspaces await local data connections.</p>');
$('#help').onclick=prototypeInfo;
render();
